name       : pcaudiolib
version    : 1.0
release    : 4
source     :
    - https://github.com/rhdunn/pcaudiolib/archive/1.0.tar.gz : df2d0eb5de856dbdb7ffb4eb460dd65ea35ccdedc314854df469bc1ac4ad2c05
license    : GPL-3.0
component  : programming.library
summary    : Portable C Audio Library
description: |
    Portable C Audio Library
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libpulse-simple)
setup      : |
    %patch -p1 < $pkgfiles/build-fixes.patch
    %reconfigure --with-pulseaudio --with-alsa --disable-static
build      : |
    %make
install    : |
    %make_install
